name: Nix Chore
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  nix-flake-update:
    name: "Nix Flake Update"
    runs-on: ubuntu-latest
    steps:
      - name: "Nix Chore Action"
        uses: Thammachart/nix-chore-action@main
