on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  nix-chore:
    runs-on: ubuntu-latest
    steps:
      - uses: Thammachart/nix-chore-action@main
